# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('customer', 'Customer'), ('dealer', 'Dealer'), ('SE', 'Service Engineer'), ('analyst', 'Analyst'), ('expert', 'Expert')], default='Customer', max_length=20)),
                ('userid', models.CharField(max_length=20)),
            ],
        ),
    ]
